// This file was auto generated by ts-helper
// Do not modify this file!!!!!!!!!

import ExtendObject from '../../../app/extend/application';
declare module 'egg' {
  interface Application {
    applicationShow: typeof ExtendObject.applicationShow;
  }
}