// This file was auto generated by ts-helper
// Do not modify this file!!!!!!!!!

import ExtendObject from '../../../app/extend/request';
declare module 'egg' {
  interface Request {
    requestShow: typeof ExtendObject.requestShow;
  }
}