// This file was auto generated by ts-helper
// Do not modify this file!!!!!!!!!

import ExtendObject from '../../../app/extend/response';
declare module 'egg' {
  interface Response {
    responseShow: typeof ExtendObject.responseShow;
  }
}